update dockerfile and scripts for docker run

diff --git a/scripts/esd-start-container b/scripts/esd-start-container
--- a/scripts/esd-start-container
+++ b/scripts/esd-start-container
@@ -1,21 +1,42 @@
 #!/bin/bash
 
-status=0
-
-if [ -z ${ESD_REPO} ]; then
-    echo "ESD_REPO Not Set"
-    status=1
+XAUTH=/tmp/.docker.xauth
+if [ ! -f $XAUTH ]
+then
+    xauth_list=$(xauth nlist $DISPLAY)
+    xauth_list=$(sed -e 's/^..../ffff/' <<< "$xauth_list")
+    if [ ! -z "$xauth_list" ]
+    then
+        echo "$xauth_list" | xauth -f $XAUTH nmerge -
+    else
+        touch $XAUTH
+    fi
+    chmod a+r $XAUTH
 fi
 
-
-if [ $status = 0 ]; then
-    docker run -itd \
-        -v /dev:/dev \
-        -v ${ESD_REPO}:/workspace \
-        -w /workspace \
-        --name esd \
-        --privileged \
-        esd-2020
-else
-    echo "Container Not Started"
+# Prevent executing "docker run" when xauth failed.
+if [ ! -f $XAUTH ]; then
+    echo "[$XAUTH] was not properly created. Exiting..."
+    exit 1
 fi
+
+if [ -z $ESD_IMAGE_NAME ]; then
+    ESD_IMAGE_NAME=esd-2020:latest
+fi
+
+if [ -z $ESD_CONTAINER_NAME ]; then
+    ESD_CONTAINER_NAME=esd
+fi
+
+docker run -itd \
+    -e DISPLAY=$DISPLAY \
+    -e QT_X11_NO_MITSHM=1 \
+    -e XAUTHORITY=$XAUTH \
+    -v "$XAUTH:$XAUTH" \
+    -v "/tmp/.X11-unix:/tmp/.X11-unix" \
+    --net host \
+    -v /dev:/dev \
+    -v /:/hostroot \
+    --name $ESD_CONTAINER_NAME \
+    --privileged \
+    $ESD_IMAGE_NAME
